name = "chat-latino-backend"
main = "src/index.ts"
compatibility_date = "2024-03-15"

# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "chat-latino"

# Variables
[vars]
S3_ACCESS_KEY_ID = "3cd44d5245554ad31ecdb73d4b3c40b7"
S3_SECRET_ACCESS_KEY = "ad5b79b1916db68d580a51b02e532bcf5d5ec26d2a58e2e931c3e379038ea57f"
S3_ENDPOINT = "https://1293e708f0dd291ae3c8da2be92d0ff5.r2.cloudflarestorage.com"
JWT_SECRET = "supbase-jwt-secret-for-auth"
